# Generated by Buildr 1.3.5, change to your liking
# Version number for this release
VERSION_NUMBER = "1.0.0"
# Group identifier for your projects
GROUP = "gmail-checker"
COPYRIGHT = ""

require 'buildr/scala'

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://www.ibiblio.org/maven2"

COMPONENTS = transitive('org.apache.httpcomponents:httpclient:jar:4.0.1')
HTTPCLIENT = transitive('commons-httpclient:commons-httpclient:jar:3.1')

desc "The Gmail-checker project"
define "gmail-checker" do

  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT
  compile.with COMPONENTS, HTTPCLIENT

  package :jar

  task :run => :compile do
    Java::Commands.java('org.reliant.gmail.GmailChecker', :classpath => compile.dependencies + [compile.target.to_s])
  end
#  task :run => :compile do
#    system 'scala -cp target/classes org.reliant.gmail.GmailChecker'
#  end
end

# vim: set ts=2 sw=2 et:
